Allow condor_q to sort with negative clusterID
===GT=== #2726
Fix the bug below, noticed by Brian Bockelman:

Brian reports the following strange behavior using code from the current trunk:

$ condor_q -pool red-condor.unl.edu -name red-gw2.unl.edu -format '%s'
ResidentSetSize
Error: Two clusters with the same ID.
tempCPS: -1 -1 -1 -1
Comparing against: -1 -1 -1 -1

The bug was introduced in 99f1b69
===VersionHistory:None=== Never in a released version of Condor