Can't declare variables mid-function pre-C98
gcc was letting us do it (compiling C98 mode?), but Visual Studio said
"Ha! No!" (Actually it very helpfully said "error C2143: syntax error :
missing ';' before 'type'")